### ISSUE TITLE
Comments on DTN

### ISSUE THREAD

**Issue by NicoKos** [irtf-nwcrg/draft-irtf-nwcrg-network-coding-satellites#13]
legitimate -> legitimize.

This entire section is unnecessary. With this draft on a multi-gateway satellite system and DVB, you're talking about geostationary satellites which are always visible. Little disruption. 600ms or so delay is coped with by Internet protocols (RFC829 SATNET work etc.) So, not a significant delay issue either. It's out of scope for the abstract. And geostationary satellites generally don't use CCSDS for broadband; TDRSS is so much a special case.
Since we're not standards track, References aren't split informative/normative -- but given the DVB starting point, I'd expect to see more DVB-S references.
EN 302 307, which details extensions of the original satellite transmission standard DVB-S (EN 300 421), etc.

**Comment by elochin** [comment]
We need to discuss this point. Just corrected legitimize in #22
