### ISSUE TITLE
Comment on section 4.2

### ISSUE THREAD

**Issue by NicoKos** [irtf-nwcrg/draft-irtf-nwcrg-network-coding-satellites#15]
John Border: Section 4.2, 2nd Paragraph
 
"Unidirectional" implies (to me) no ACKs.  Without ACKs, FLUTE must do repair in such a way as to not need to know exactly what was lost.  This seems different enough to me to be explained separate from NORM.

**Comment by elochin** [comment]
Our objective is not to discuss about NORM and FLUTE, which is out of scope of the document. We cite these protocols as possible usage example. Also note that although FLUTE is unidirectional, the RFC keeps a door open proposing bidirectional communications for security purpose and to enable full reliability transfer. As a result, we move this sentence at the end of this section as a complementary material and completed the FLUTE description.
