### ISSUE TITLE
NITS

### ISSUE THREAD

**Issue by NicoKos** [irtf-nwcrg/draft-irtf-nwcrg-network-coding-satellites#16]
A few document nits…
 
Section 2, 1st and 2nd Sentences
 
“in satellite system” should be “in a satellite system”.  Not clear what “lays” means here.
 
“multi-gateway satellites network” should be “multi-gateway satellite network”.  (Most of the uses cases have nothing to do with multi-gateway, though.)
 
Section 3, 2nd Sentence
 
Delete the duplicate “where”.
 
Section 6, 2nd Sentence
 
“that the some scenarios” should be “that some scenarios”.

**Comment by elochin** [comment]
Thanks for having identified the NITS. 
Closed by PR #21
