### ISSUE TITLE
Physical layer reliability and layer 2 mechanisms

### ISSUE THREAD

**Issue by NicoKos** [irtf-nwcrg/draft-irtf-nwcrg-network-coding-satellites#5]
"However, physical layer reliability mechanisms may not recover transmission losses (e.g. with a mobile user) and layer 2 (or
above) re-transmissions induce 500 ms one-way delay with a geostationary satellite"

Look, forward error coding (FEC) and link ACKs are complementary on a sliding scale depending on delay/channel quality, and this is talking solely about retransmissions. In fact, link or channel FEC do recover a large number of transmission bit/symbol losses without adding extra delay.

**Comment by elochin** [comment]
We have clarified this point in PR #26
